### ISSUE TITLE
Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by v3lip** [ashbeech/moralis-mutants-nft-engine#12]
```
Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
    at RedirectableRequest.write ({redacted}\moralis-mutants-nft-engine-main\node_modules\follow-redirects\index.js:102:24)
    at RedirectableRequest.end ({redacted}\moralis-mutants-nft-engine-main\node_modules\follow-redirects\index.js:127:10)
    at dispatchHttpRequest ({redacted}\moralis-mutants-nft-engine-main\node_modules\axios\lib\adapters\http.js:360:11)
    at new Promise (<anonymous>)
    at httpAdapter ({redacted}\moralis-mutants-nft-engine-main\node_modules\axios\lib\adapters\http.js:48:10)
    at dispatchRequest ({redacted}\moralis-mutants-nft-engine-main\node_modules\axios\lib\core\dispatchRequest.js:58:10)
    at Axios.request ({redacted}\moralis-mutants-nft-engine-main\node_modules\axios\lib\core\Axios.js:108:15)
    at Axios.<computed> [as post] ({redacted}\NFT01\moralis-mutants-nft-engine-main\node_modules\axios\lib\core\Axios.js:140:17)
    at Function.wrap [as post] ({redacted}\NFT01\moralis-mutants-nft-engine-main\node_modules\axios\lib\helpers\bind.js:9:15)
    at {redacted}\moralis-mutants-nft-engine-main\src\metadata.js:147:8 {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'X-API-Key': '{redacted}',
      'User-Agent': 'axios/0.23.0',
      'Content-Length': 31852737
    },
    method: 'post',
    url: 'https://deep-index.moralis.io/api/v2/ipfs/uploadFolder',
    data: '[{"path":"images/0000000000000000000000000000000000000000000000000000000000000002.png","content":"iVBORw0KGgoAAAANSUhEUgAAA+gAAAPoCAYAAABNo9TkAAAABmJLR0QA/wD/AP+gvaeTAAAgAElEQVR4nOzd6ZMceX7f908edVf1feMcAHPPLGZ29pghlyKpXV5LihRJWbJES6IdIUuyIvTEtmxFWHaEFZYd9N/gB3poOyRK5iHG8lhyd3Z2du4Lg8HZjUZf6Lu77rx+fpBZ1QWggcHRaGSj368AouvIyspuVDXqk9/f7/uzfuvf/J4RAAAAAAB4rOzHfQAAAAAAAICADgAAAABAKhDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABAChDQAQAAAABIAQI6AAAAAAApQEAHAAAAACAFCOgAAAAAAKQAAR0AAAAAgBQgoAMAAAAAkAIEdAAAAAAAUoCADgAAAABACriP+wAAAAD2nDEyxkiSoijqXjdRJMkkf4xMZG7aNnlwfHtyuWeXsiyr53ar+7j49vi23sfc9Fjbii/I6r2n53L82Ph5drvtDvdbkm07sh1HsizZTnzZsqzeDQEABwABHQAApJKJIkVhqCgK48tBkNwWh+yo5zaZ5HoYKgoChZ4nv92W32zIb7cVtNsKPE9RGCj0fYW+LxNGiqJQURjv35hIJjLJZZOEacmYqJujjTFJZu4E9EiWZXe3jbP3bmHdSv5YMt2dJaG7d/PuN7/7bkxycqFzzbJsWY4jx3WVyReUKxWV7+tXcWBAxYEB5coVubm8MrmcnGxWTibTc5IBAJA2BHQAALCvjDHdIB0FgaIwUBRGCn0vvj0M5TebatdramxsqFWtqlWryms0FLTbCj1PYeArTMK5CZNwbXrC9c6T3ZZ1O8dwU3XZ3F717t5/p/s6+7j1/jvdt9u2u3nQx/Vsb0mybFu26ypbKKo4OKiBqSMaPHJUfRMTKvT1y83l4qo7ACA1COgAAGBvJQE8DANFfqAwCeFBqyWv1VJza0uNzQ01NtbV2t5Wu16X32wq8NqKgvhx3WHnnSp2st+7BuO7HdItXzvH+WXfx5fet9s2d7rvXo/3QR/Xs72RZJKTHUG7rcbmhtZmpmXZtrLFkvonJzV25mmNnjqt0vCwMtkcw+EBIAUI6AAA4P71DCmPh4x7CjxPfrOp1va2amtrqq2uqLG5oVatKr/Ziivf4c6QdNOzr/t53vt+DCTFowZMGKpV3VarVtXy5Usq9PVp7OlndezsKxo8ekxuNvu4DxMADjUCOgAAuDOzM9e7M3fbazbUrtdVX1vV9vIN1VZX1dzakteoK/C8eJh5FD1YAMf+SEYoNDY3de29d7T0xec68drXdPJr31BxYFCWzUI/APA4ENABAICk3rnhvoJ2Ug2vVVVbjYN4dfmGGpub8poNhZ4XV2R7hqHjYDLGqFWt6tIPf6CtxSU9/51f0MDkFCEdAB4DAjoAAIdQp0N64HkK2i15zabq62uqLi9ra2lRtdUVtbarceO23iHphy6M37ps2m7LqO2+tFpPS7p72PZ+9733oijS0sUv5DXqeumXv6vhEycJ6QCwzwjoAAA84UzPXHG/3ZJXr6u2uqqtxQVtLi6ovr6mdr2u0PcPUBC/Jfxa9k1LmFmWk3y1k67mtpRclixZlhNvY1nxNrLifVjJdj376DRPs2R1H3/zcez0h7esztronduiZLtO0I1uflx3ebZkybbOc/TcHn+bna7zvfuxZUzSUC/yFAVtRVFbJvJlokAmCnVf4T55zvW56/rkj/5AL3/31zTy1CmWZQOAfURABwDgCdMN461mHMbX1rS1tKDN+XnV1tbUrtfidcBTNzw9CYKWlQTVODBbliPLycnu/M2U5GRKcjIVOdmy3Nyg3NyA3NygMoURudkBOdmybCef7MPpBnXJkmW7kjGybEfGJGuJ265MFCZhPT4GddY3vy0k337Zsux4vfTubVG8TxPdtr3VE/DNXQJ0Z7vuPqRdnyf+EsqYQCb0FIUttesLam1eVn39czU3L6pdm1PkN5J9fXn3+s3FBX32J3+ss3/jNzR45CiVdADYJwR0AAAOMBNFCoNAQbstr9lQc3NTW0uL2pifU3V5Wc2tLQVeO+6cfr/rae85q1uxtixHlp2R7RbkZErdcJ0tTihXPqps+YiyhTE52T7ZbkGWnUke48h2cpIsWU4mud1NQrYjy3J3qXIfPhUZRaEnE3oK/aratXk11s9pc/6vtL30toLmmowJ77wDY7QxP6dP/9Mf6uyv/roGpo6wDBsA7APrt/7N76Xp1DkAALiLTnU8aLfUqla1vXxDm/Pz2lycV31tXX6zoSjpov547IRw287KzpTk5vqVKYwrVz6iQv9p5ftOKlOckJuEb9vJyXKycWB3cnHott2doefYEyYKFPo1tbZntDb9B1q59H/Lqy/prhV1y9LoqdM6+2u/rsrYOMPdAeARI6ADAJBWxigMQ4WeJ69RV2NrS9tLi9qYm9PW0mK3Ot5ZMmt/xUHNdnNy3LLcXL+y5SPKV06qMPiM8n1PKVscl5OpyHayspycHLcQD1W3M9153ngcjKKgre2lH+v6e/+7qssf6MtC+tTzL+ilX/k1lYeGqKQDwCPEEHcAAFKis8xZ0G4nc8dXtbkwr/Xr11VduaF2raYoDPdx7njcyCweWu7KyVSUKQwr3/eU8v1nVBp6QbnKMbn5YTluIa6Gu4U4kNsZUf1OK0u2m9fAkZ+VmxvUzNv/StuLP9YdQ7oxWjz/udxcXi/+4i+r0NdHSAeAR4SADgDA42JMPH/c89SuVVVdWdHmwrw2rs+qurIir1HfCeT7wkrmeOfl5oeUrxxTYfA5lYZfUqH/tDKFUdluUY5blOXm4+HonU7nh1nvSmi7rayWVpat8uhZPfXG/6bpH/9P2l76cbfp3K2MMZr75CPlSiU987M/r1yptM8HCwCHAwEdAIB9YoxRlATy5tamaqur2pi7ro35OdVWV+Q1mzJhuD/LnCWN2my3oExhRIX+MyqNvKzi4PPKVY4rkx+Kh6d35ojbfGSQtPuy5OYOlw8ES6Xhl3TyjX+t6bf+papL7+hO30QUhpp+523lKxWdev2n5GQy+3uoAHAI8L8tAACPSO+Q9U6FfP36rNavX1NtdVV+s6ko6lmG65FJKuNuQZn8iAoDT6s08rJKQy8qVzmRhPGy7EyJ+eFf5sAF8Htg2SoPv6yTr/+vmn7zX6i2+vEdNw08Txd/8Jcq9A9o6sWXZDuMoACAvURABwBgj3QCedhuq12vq7a6oo35Oa1dm1F1ZVleoyETRY94yHqyjJmTkZsbVKH/lIrDL6s8clb5/tPxOuGZCmEcN7NslUdf1ck3/rWu/PC/VXPz0h03bdfrOve9P1GuVNLIqdN0dgeAPURABwDgIURJl/VWvaZ6MmR9/fqstpeTpm5R9Air43Ewihu4lZQrH1Nx6HmVR86qOPS8sqVJubkhOZlSvIwZ88VxF5blqDLxuk5843/W9Fv/Uu3a3B23rW+s6/M//55eLf2W+sbHaRoHAHuEgA4AwH0wUaTA9+Q3m6qvr2tzYV5rM9PaWlpUq1pVFASPsEIerzFu20l1fOC0SiOvqDz6ivL9p5UtjMnJlGS7RVm2I7qo435ZlqOBY9/Wsa/9j5r58b9S0N7YfUNjtD47q0tv/pVe+uVfVa5c3t8DBYAnFAEdAIC7MFGkMAjkt5pqbm1pa2FBa7PXtDk/p8bWpkLfl4l273z98OJA7jh5ZYrjKg4+q/LYayoNJ3PHC6Ny3KJsJ8dQdewZ28lp5PRvyW+u6Pr7v6coaO66nYkizX3yscqjYzrzU9+iaRwA7AECOgAAt+gMW29Wt1W9cUOr12a0PntN9bU1+e3WIwzk6nZWz5amVBp5WeWRV1Qa+Ypy5SNys/3x3HEnK6rjeJRsJ6exZ/+e2tU53fji38pEwa7bhUGgyz/6oSqjY5p49jmaxgHAQyKgAwBgjMIwlN9oqL65oc35Oa1cvaLN+Xm1alVFYfjI5pFbliM7U1SufFTlkbNxhXzoRWXLU3EgdwuybCqT2H+Z/LCmzv4ztWtz2pj9nu7Uwr5dq+nC9/9c5aFh5qMDwEMioAMADiUTRQp9X+16XdWVG1qdmdbazIyqy8txldyYRxLKdwL5MZVHX1Fl/OsqDr2oXGlKTrYi28mz5jhSwlK+clzHXvsX8urzqq99dsctNxcXdOUnb+nFX/hlZYvFfTxGAHiy8AkAAHA49KxJ3tjc0ObiglauXtHG9etqbm8pDIJHF8jdvLKlSZVGXlHfxDdVHHpB+cpxOdk+AjlSzlJp+CUd/ep/p6tv/vfymyu7bmWiSHMff6ThEyd19OWzDHUHgAfEJwIAwBPLGKMoCOQ3m6qtr2ltZkYrVy9ra2mxuyb5nrNs2U5O2eK4SiNfUd/4N5M55Efl5gZlu3mGrONAsWxXA8e+rcmX/4nmPvg/FQWtXbfz221dfvOHGpg8Eg91BwDcNwI6AOCJ0jt0ffvGklanr2p1ZlrVleW44/ojGLpuOzllCiMqDj6vysTrKo++qnzfCbn5ITluMamQMy8XB5fjFjX+7O+ouXFBq5f/nYwJb9/IGG0tLWr63Z/ohe/8ojL5/P4fKAAccAR0AMCBZ6JIgeepubWlzcV5rV69qrXZGTU2NvZ4XfJ42TPLcuXm+lUYeEZ9419Xeew1FQaejpc9yxSTCjmBHE+WTGFER87+c9XXzqmxfm7XbeKl1z7S2JkzmnjmOVk2y/8BwP0goAMADh5jFEWR/FZLjY11bczPaeXKZW3MXVerVou7rifb7YXO0mf5vqdUGf+G+ia+qcLgM8qWJuW4ZdluTgRyPPksFQae1tTL/0TTP/ofFAaNXbdq1+uaeecdDU4dVb6vb5+PEQAONgI6AOBgSEK512iotraq9euzWrl8SZuLC/KbTUVRtIdD1y1ZtqtMfkilkbPqm3xDlbHXlKskw9advGRRGcThY9muBk/8krYWfqiVS//P7hsZo+Url7R04byOf/VrNIwDgPtAQAcApFenUt5sqrq6orWZaS1fvqStpUX5rT1eCi1p7pavnFBl/Ovqm3hDpdGzyhbG5GTLsuzsQ+xbd1pCGjhwMvlhTb74j1Rd+ola1Wu7bhP6vqbf+YlGTp1WeXhkn48QAA4uAjoAIHWiMOx2Xl+9elU3Ll3Q1tKigk4o3yOW5cjNDag49IL6p76lysQ3le87KTc3FHdbt+6j8tcZ4W50eyAnnOMJUxp5SePP/0PNvvd/yETerttsLi5o/rNPdeanviUnw8oFAHAvCOgAgMfPGIVhKL/ZUG1tTavTV7uV8r0N5ZZsJ6tsaUrl0VfUP/UtlUZfVa58RG62796bu1mSlRyT6WxPIMchYtlZjZz+TW3Mfk/bS2/vuo2JIs28+47GTp/R4JGjkkWfBgD4MgR0AMBjE4VhPKd8dUWr01d14/JFbS/dUOC1926NcsuW4+SV6zuh/smfVt/Uz6g49LyyhTHZbiFZAu1e9tNz2UjGsgjiONSypSmNv/C7qq99ptCv7bpNfWNd195/T+XhEWUKhX0+QgA4eAjoAIB9ZXoava1OX9WNSxf3vFJuWY6cTFmFwWfVN/lT6pt8Q8XBZ5XJj8p2sg/W4O3WQyOc45CzbFcDR35eA8f+utam/1Ayu5xUM0bz5z7V5AsvauzM07KoogPAXRHQAQCPnEmWRKtvrGttZlo3Ll7QxsK8/GZzzyrllp2RmxtQafjleD75+NeU7z8tNzcYh/J7XQaNhm7APcsUhjXx/O9qe/Et+c3VXbfx6nVde+9dDUxOKVcu7/MRAsDBQkAHADwSxhgFXluNjQ2tz17T0sUL2rh+Xe16bY9CuSXLzihTGFFl/GsaOPJzKo++qlz56MN1XSecA/fBUnnsaxo5/ZtaPPd/7VpFN8boxqWLWrs2o6kXXmQuOgDcBQEdALBnjDEKfV+talWb89e1eP5zrc7MqF2r7sE65XFp27KzyhbHVZn4pgaO/rzKI19RrnxUtlu89/nkAPaMkylp7Nnf0cb1P1dr6+qu2/jtlq69/56GT5ykig4Ad8EnGQDAQ4vCUF69rq2lBd24dEk3Ll5QY2NdYRjuwTrlcef1THFclfFvaPDYt1UefVXZ4rjsTOn+lkID8EgUBp7R2DN/V9ff/z2ZyL99A2O0cvWyVqevauqll5mLDgB3QEAHADyQzrzy2uqKli9f0tLFC6reuCG/3XrIPccf3C07o1z5iPomXtfA0Z9TaeSssqWp+1+fHMAjZzs5DT/161q7+h9VXzun3eaKBJ6nqz/5sYZOnFChr3//DxIADgACOgDgnnWGsMfzyme0eP681udm5TUacQf2h6yWW3Y2DuWTb3TnlGdKE3Kc/IN1Xgewb/J9JzT27O9o5u3/RSbydt1mbfaalr44rxOvfV22w4k2ALgVAR0AcHfGKApDtWo1bc7PaemL81q+elmt7e09mVdu2a6ypUn1jX9TA8e/rfLIWWVLR+S4BUI5cIBYdkZDJ39Fq1f/g6pL72i3KnoUBJp5712NnXlGpaGh/T9IAEg5AjoAYFcmihS026qtrerGpYtaPP+5qss3FPj+HlTKXWXyI6qMf10DR39OlfFvKFc+JjtTZPg6cIBli5OaeO4fqr76saJg9+kuW4sLWjx/Tqe++YZsl4+iANCL34oAgB3GKAxDtba3tDF3XQvnzml15qra9fpDL41mWY7c3IDKY1/V4LFfUGX868pVjsvJlOm+DjwhLNvVwLFvq3/qr2lj9k+1axU9ijTz/rsae/oZ9Y2OsewaAPTgExEAIG741mxqe/mGli9f0uIXn6u2sqIwCB5qv5Zly86UVBx6QUPHf1F9Uz+jQt9TcrIVWXZmj44eQJpkCsOaeOF3tb30tkJv+/YNjFFtZUUL5z5T6Vt/TU6G3wUA0EFAB4DDKqmWNzY3tDZ9VQvnP9f6tWvyW8244dsDs2S7OeX7Tmnw2Lc1cPTnVRx6QW5ugFAOHAqW+ibe0OCxb2v1yn/QrlX0MNT1Dz/Q1PMvqm9iYv8PEQBSioAOAIeMMUZ+s6mtpUUtXfhCS1+cV3197aEbvll2RtnihPqnvqXB47+o8ugryhTGZLs5dZZOAw4OIxOFMiaUTCQT+TImiq9HoYxMdxspkjGd94/puRztnOwy8WgU03ms2Xm/GZm494Jlxbd1hnz3XLY676HebW59v1qWLMuWZEmWLctykv3asmwnvl2WLNuRZbnx9j3bdh9j25LseF8P2KjRyVY09szf1db8D+S31nbdpra+prnPPtGzw8NU0QEgQUAHgMPAGEVRpFZ1W2szM5o/96nWZqZ3lkd7QPG88kGVx17T0IlfVGXideXKR2W7BZq94TFLAnbky0SBjAllTNC9LQ7dgaLO5SSIR5EvE7YUeFUF7U35zWX5zTWF3qYCr6rQr8mE7eSxXrzv3ueIAsmESUiPdkK+TPc5ZEwS8BVf74bu3cNwHKItGRPdHNSTe3vncHeDtiwpCeK2nZFlu/FfJxdfd/Ky3bxsJyvbLcpxC7Ldktxsn5xsWU62X062IsctyXaLst2cLCvZh+XIcrLdkwq2k9+53XZl2RlZlqPy2Fc1cOzbWrn0/2q3KrqJIl3/6ANNPf+CBqaOMBcdAERAB4AnmjFGgddWfXVVSxcvaOHcZ9q+sfTQ1XLHLao49LwGT/yy+o/8rAr9p+Rk+wjleMRMEohDmciLA3Lo7wTlJDiHQV1Be0t+c1nt2rz8xg0F7Q0F3rYiv6EwaCgKmvE+Qk8m9GRkdoJ7J1zL7PI+MYor0bt9PQh6j3WXQNxTmbc6JwysnWp6J5zHIT8XB/tMSU6mokxuUG5+SJnimLKFMbn5YZWGX9TG7PcUtDd3PZrG5qZmP/pQpZERZXL5vf92AeCAIaADwBPIRJFa1ao25+c0f+4zLV+5pHat9lCd2C3LUbY0qYGjf11DJ7+r0vCLyhRGknnlVL7wcIwJ47AdNmVCX2HQSG7zZKL4etDakFdfULu+IK++IK+xpKC9qdCrKgoaisK2orDdrYgb03siai8D9K37PCjhXLr5WHc57p4TEnHlX/GIgN5t/N3223uyQjcPtzd3/r1jokjzn36iIy9/RcPHT9zLNwAATzQCOgA8KYxRFIaqr69rZfqK5j/9RBvzcwo878Gr5ZYtJ1NSafgrGj75XfUf+WvKVU7IyRRFKMf96A4JD9uKgpaisKUo9BQFTQXtDbVr82pXZ9TanlG7vqCgta7Q2/6S0N3d+2P5ntDrlpMVJpmLfw9a1W1d/+hD9Y9PyM3lHs3hAcABQUAHgIPOGPmtlqory1q68IUWPv9MtdXVhxjGbsmyXeUrx9V/9Oc0dOKXVRx6QZn8MF3YcUed+dfdSnbQVBS2Ffp1Be0NebV5Nbeuqr'... 31842737 more characters
  },
 ...
```

**Comment by RobJay67** [comment]
Sorry to bug you v3lip but does your index,js file have all the code in it mine seems to be short at 97 lines long

**Comment by v3lip** [comment]
@RobJay67 All the lines? All the lines that should be there, are there. What exactly is your issue?

**Comment by RobJay67** [comment]
In the video when he is done with config.js and opens index.js I only have 96 lines of code and he scrolls down to 260 to make a vital code change. When I look at the index.js on Github I also only see 96 lines of code... where am I going wrong to not generate the rest of the code?

**Comment by v3lip** [comment]
> In the video when he is done with config.js and opens index.js I only have 96 lines of code and he scrolls down to 260 to make a vital code change. When I look at the index.js on Github I also only see 96 lines of code... where am I going wrong to not generate the rest of the code?

We're not generating any code, we're downloading it, and you get it as it should be. This code is probably more updated and optimized than what is was previously at the point pf the video. Just go through the files and look for different calls or functions and what not. Im sure you'll figure it out. :)

**Comment by Lalaith15** [comment]
Have the same issue - did you were able to resolve it?

**Comment by xaser3d** [comment]
The script works well only for 10 images 500 kbytes each. When I try to generate more, I get an error from the server that the limits have been exceeded. Max buffer size from server message is:   maxBodyLength: 10485760, My buffer size is  'Content-Length': 53120297 for 100 images.
Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
    at RedirectableRequest.write (C:\moralis-mutants-nft-engine-main\node_modules\follow-redirects\index.js:102:24)
    at RedirectableRequest.end (C:\moralis-mutants-nft-engine-main\node_modules\follow-redirects\index.js:127:10)
    at dispatchHttpRequest (C:\moralis-mutants-nft-engine-main\node_modules\axios\lib\adapters\http.js:360:11)
    at new Promise (<anonymous>)
    at httpAdapter (C:\moralis-mutants-nft-engine-main\node_modules\axios\lib\adapters\http.js:48:10)
    at dispatchRequest (C:\moralis-mutants-nft-engine-main\node_modules\axios\lib\core\dispatchRequest.js:58:10)
    at Axios.request (C:\moralis-mutants-nft-engine-main\node_modules\axios\lib\core\Axios.js:108:15)
    at Axios.<computed> [as post] (C:\moralis-mutants-nft-engine-main\node_modules\axios\lib\core\Axios.js:140:17)
    at Function.wrap [as post] (C:\moralis-mutants-nft-engine-main\node_modules\axios\lib\helpers\bind.js:9:15)
    at C:\moralis-mutants-nft-engine-main\src\metadata.js:147:8 {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'X-API-Key': 'gV36paHDAJcmrLrnPjNYXO6ACfEOCXJNJGCfarl0aU6Y0fpiCU4TzpkYwh2AqqYK',
      'User-Agent': 'axios/0.23.0',
      'Content-Length': 53120297
    },
    method: 'post',

**Comment by xaser3d** [comment]
Early in 2021, I see that the buffer size from the server was maxContentLength: -1 This turns out to be a server limitation? How to remove this restriction I need to upload 10,000 thousand small pictures.

**Comment by xaser3d** [comment]
Can you edit your scrip to upload chunks maxBodyLength: 10000000 ?

**Comment by Wakdman** [comment]
Have you found a way to correct this error message Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit ?
