### ISSUE TITLE
node index.js is giving me an error! Little help here good people!

### ISSUE THREAD

**Issue by Kush1399** [ashbeech/moralis-mutants-nft-engine#14]
kushagrashiv@Kushagras-Air moralis-mutants-nft-engine % node index.js
node:internal/modules/cjs/loader:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/kushagrashiv/Desktop/moralis-mutants-nft-engine/node_modules/canvas/build/Release/canvas.node, 0x0001): tried: '/Users/kushagrashiv/Desktop/moralis-mutants-nft-engine/node_modules/canvas/build/Release/canvas.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/canvas.node' (no such file), '/usr/lib/canvas.node' (no such file)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/kushagrashiv/Desktop/moralis-mutants-nft-engine/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/kushagrashiv/Desktop/moralis-mutants-nft-engine/node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by J-Renegade** [comment]
did you install node into the package?

**Comment by GaloisField2718** [comment]
I have the same issue and everything seems up-to-date. 
Just one thing more : 
`moralis-mutants-nft-engine/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).`
And the same thing at the bottom. 
I don't know if I have to downgrade `node`
`node --version
v16.13.`
Have you some ideas ?
